--COMENTARIOS
/*
COMENTARIOS MULTILÍNEA
*/
/*select * from dept
SELECT * FROM EMP where apellido = 'sancha'
AND oficio = 'empleado'*/
--TODOS LOS REGISTROS DE UNA TABLA CON TODAS SUS COLUMNAS
select * from dept
/*EN BBDD SE UTILIZA LA OPTIMIZACIÓN DE CONSULTAS.
CONSULTAS IGUALES (DEVUELVEN LO MISMO), NO SON IGUAL
DE EFICIENTES (VELOCIDAD)*/
--ESTA ES MÁS RÁPIDA
select dept_no, dnombre, loc from dept
/*FILTRADO DE DATOS:
SOLAMENTE INCLUIREMOS UN WHERE
OPERADORES DE COMPARACIÓN*/
/*
> MAYOR >=
< MENOR <=
<> DISTINTO
= IGUAL
*/
--TODO LO QUE NO SEA NÚMEROS, VA ENTRE COMILLAS SIMPLES AL COMPARAR
--MOSTRAR TODOS LOS EMPLEADOS DEL DEPARTAMENTO 10
select * from emp where dept_no = 10
--SI ES OTRO DATO DE COMPARACIÓN NO NÚMERO
select * from emp where fecha_alt > '10/01/1986'
/*OPERADORES RELACIONALES
AND	TODAS LAS CONDICIONES SE CUMPLEN PARA FILTRAR
OR	SE CUMPLEN CADA UNO DE LOS LADOS DE LA CONDICIÓN
NOT	MALA PRAXIS*/
--MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10 QUE COBREN MÁS DE 400000
select * from emp where dept_no = 10 AND salario > 400000
/*SI LO HACEMOS CON UN OR...
RECUPERARÁ LOS EMPLEADOS DEL DEPARTAMENTO 10 Y TAMBIÉN
RECUPERARÁ LAS PERSONAS QUE COBREN MÁS DE 400000*/
select * from emp where dept_no = 10 OR salario > 400000
--MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10 Y DEL 20
--SIEMPRE QUE PREGUNTEMOS POR UN MISMO CAMPO, ES UN OR
select * from emp where dept_no = 10 OR dept_no = 20
--NOT NIEGA UNA CONDICIÓN
--MOSTRAR LOS EMPLEADOS QUE NO SEAN DIRECTORES 
select * from emp where NOT oficio = 'director'
--MÁS EFICIENTE (VELOCIDAD)
select * from emp where oficio <> 'director'
--OTROS OPERADORES
--OPERADOR IN: BUSCA VARIAS COINCIDENCIAS PARA UN CAMPO
--ES IGUAL A UN OR
--MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10 Y DEL 20
--, 30, 66, 78
--select * from emp where dept_no = 10 OR dept_no = 20 OR dept_no = 30 ....
--CAMPO IN (VALOR1, VALOR2)
select * from emp where dept_no IN (10, 20, 30, 66, 78)
--OPERADOR NOT IN
--MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO QUE NO SEAN 10 Y 20
select * from emp where dept_no NOT IN (10, 20)
--NO DEBEMOS CONFUNDIRLO CON NOT
select * from emp where NOT dept_no IN (10, 20)
--OPERADOR PARA RANGOS PERO NO ES STANDARD
--BETWEEN
--BUSCA ENTRE DOS RANGOS INCLUSIVE
--MOSTRAR TODOS LOS EMPLEADOS QUE COBREN ENTRE 162500 Y 208000
select * from emp where salario BETWEEN 162500 AND 208000
--PREFERIBLE UTILIZAR >= AND <= PARA LA MIGRACIÓN
select * from emp where salario >= 162500 AND salario <= 208000
--OPERADOR LIKE
--INTENTAR EVITARLO PORQUE NO UTILIZA ÍNDICES
--SIRVE PARA REALIZAR BÚSQUEDAS EN UN CAMPO TEXTO POR COINCIDENCIAS
--UTILIZA CARACTERES ESPECIALES
-- % CUALQUIER CARÁCTER Y LONGITUD
-- _ UN CARÁCTER (CUALQUIERA)
-- ? UN CARÁCTER NÚMERO
--QUEREMOS BUSCAR LOS EMPLEADOS QUE SEAN COMO REY
select * from emp where apellido = 'REY'
select * from emp where apellido LIKE 'REY'
--QUEREMOS BUSCAR LOS EMPLEADOS QUE SEAN COMO REY O REINA
select * from emp where apellido = 'REY'
select * from emp where apellido LIKE 'RE%'
--QUE EMPIECE POR A
select * from emp where apellido LIKE 'A%'
--QUE SU LETRA 4ª SEA A
select * from emp where apellido LIKE '___A'
--CAMPOS CALCULADOS
--SON COLUMNAS QUE NO EXISTEN EN LAS TABLAS, PERO QUE PODEMOS
--CALCULAR Y UTILIZAR A PARTIR DE OTRAS
--JAMÁS DEJAREMOS UN CAMPO SIN NOMBRE DE COLUMNA
--EL NOMBRE DE LA COLUMNA VA SIN ESPACIOS NI _ O METIDA ENTRE []
select apellido, salario, comision, salario + comision AS total from emp
select apellido, salario, comision, salario + comision AS [total de dinero] from emp
--SOLAMENTE PODEMOS UTILIZAR UN WHERE CON LOS CAMPOS DE LA TABLA
--PARA FILTRAR POR CAMPOS CALCULADOS, SE UTILIZA EL MISMO CÁLCULO
--LA CLÁUSULA ORDER BY , ORDENA DATOS DE LA CONSULTA
--SIEMPRE SE ESCRIBE AL FINAL DE CUALQUIER CONSULTA
--ORDER BY ORDENA SOBRE LOS CAMPOS DEL SELECT, LO QUE IMPLICA QUE
--PODEMOS ORDENAR POR CAMPOS CALCULADOS (ASC POR DEFECTO)
select apellido, salario, comision, salario + comision AS total from emp
where salario + comision > 30000 ORDER BY salario DESC
select apellido, salario, comision, salario + comision AS total from emp
where salario + comision > 30000 ORDER BY TOTAL DESC
--PODEMOS ORDENAR POR MÁS DE UN CAMPO SEPARADOS POR COMAS
select * from emp ORDER BY DEPT_NO, OFICIO
--ESTO NO ES UN STANDARD. CADA BASE DE DATOS TIENE UN SÍMBOLO
--PARA CONCATENAR
--EN SQL SERVER ES +
select apellido + ' ' + oficio as descripcion from emp
--TENEOMS FORMAS TAMBIÉN DE INDICAR COLUMNAS CON VALORES
--REPETIDOS, QUE MUESTRE SOLO LOS DIFERENTES
--SE UTILIZA LA CLÁUSULA DISTINCT
--SE ESCRIBE EN EL SELECT Y SE SUELE UTILIZAR CON UN SOLO CAMPO
--O CON CAMPOS COMPATIBLES ENTRE SÍ
select distinct oficio from emp
select distinct apellido, oficio from emp