--
--CONSULTAS DE AGRUPACIÓN / FUNCIONES DE AGRUPACIÓN
--
--MOSTRAR EL RESUMEN SOBRE UN DETERMINADO GRUPO
--NUNCA MUESTRAN LOS DATOS QUE CONFORMAN EL GRUPO
--PERMITE AGRUPAR POR CAMPOS DE LA TABLA
--SE DEBE UTILIZAR LA CLÁUSULA GROUP BY
--COUNT(CAMPO): MUESTRA EL NÚMERO DE REGISTROS
--NO CUENTA VALORES NULOS
--COUNT(*): MUESTRA EL NÚMERO DE REGISTROS
--CUENTA LOS VALORES NULOS
--SUM(NUMERO): SUMA TOTAL DE UN CAMPO
--AVG(NUMERO): MEDIA DE UN CAMPO
--MAX(CAMPO): MÁXIMO VALOR DE UN CAMPO
--MIN(CAMPO): MÍNIMO VALOR DE UN CAMPOS
--TODAS LAS FUNCIONES DE COMUNICACIÓN DEBEN DE TENER UN ALIAS
select count(*) AS registros from dept
select count(dept_no) AS numeroregistros from dept
--PODEMOS COMBINAR VARIAS FUNCIONES EN UNA MISMA CONSULTA
select count(emp_no) AS [numero de empleados], MAX(salario) AS [maximo salario] from emp
--ESTAS FUNCIONES NOS PERMITEN AGRUPAR LOS RESULTADOS POR UNO O VARIOS CAMPOS
--RECUPERAR EL NÚMERO DE EMPLEADOS QUE EXISTEN POR CADA OFICIO
--LA CLÁUSULA GROUP BY SE ESCRIBE SIEMPRE DESPUÉS DEL FROM
--EL TRUCO ESTÁ EN ESCRIBIR EN GROUP BY TODOS LOS CAMPOS QUE NO SEAN UNA FUNCIÓN
select count(*) as empleados, oficio from emp group by oficio
--FILTRAR POR CAMPOS DE AGRUPACIÓN
--SE UTILIZA WHERE SI FILTRAMOS POS UN CAMPO DE LA TABLA Y
--SE UTILIZA HAVING SI FILTRAMOS POR UN CAMPO DE LA AGRUPACIÓN
--WHERE SE ESCRIBE DESPUÉS DE FROM
--HAVING SE ESCRIBE DESPUÉS DE GROUP BY Y SE PUEDEN COMBINAR LOS DOS
--CONTAR EL NÚMERO DE PERSONAS POR CADA OFICIO. INCLUIR SOLAMENTE A ANALISTAS Y DIRECTORES
select count(*) as personas, oficio from emp where oficio in ('analista', 'director') group by oficio
--SI ESTAMOS FILTRANDO POR UN CAMPO DE LA CONSULTA DE AGRUPACIÓN, SE DEBE UTILIZAR HAVING (RENDIMIENTO)
select count(*) as personas, oficio from emp group by oficio having oficio in ('analista', 'director')
--MOSTRAR EL NÚMERO DE EMPLEADOS POR OFICIO DE PERSONAS QUE SE HAYAN DADO DE ALTA DESPUÉS DE 1985
select count(*) as personas, oficio from emp where fecha_alt > '01/01/1985' group by oficio
--MOSTRAR EL NÚMERO DE EMPLEADOS POR OFICIO. SOLAMENTE MOSTRAREMOS DONDE TENGAMOS 2 O MÁS PERSONAS TRABAJANDO
select count(*) as personas, oficio from emp group by oficio having count(*) >= 2