--
--CONSULTAS DE ACCIÓN
--
--INSERT: INSERTAR REGISTROS
--UPDATE: MODIFICAR REGISTROS
--DELETE: ELIMINAR REGISTROS
--
--SINTAXIS INSERT:
--NO EXISTE INSERT MÚLTIPLE STANDARD, 5 FILAS, 5 INSERT
--1) ALGUNOS CAMPOS DE LA TABLA
--INSERT INTO TABLA (CAMPO1, CAMPO2) VALUES (VALOR2, VALOR2)
insert into dept (dept_no, loc) values (60, 'Almería')
--2) TODOS LOS CAMPOS DE LA TABLA EN ORDEN
--INSERT INTO TABLA VALUES (VALOR1, VALOR2, VALOR3)
insert into dept values (61, 'I+D', 'Murcia')
--PODEMOS UTILIZAR SUBCONSULTAS PARA LA INSERCIÓN DE DATOS
--INSERTAR UN NUEVO DEPARTAMENTO QUE GENERE AUTOMÁTICAMENTE
--EL ID LIBRE DE LA TABLA
insert into dept values ((select max(dept_no) + 1 from dept), 'RRHH', 'Gijón')
--ESTO NO ES STANDARD, PROPIO DE SQL SERVER
--INSERTAR VARIOS REGISTROS CON UNA SOLA CONSULTA
--LOS REGISTROS DEBEN ESTAR EN OTRA TABLA
--1) INSERT...SELECT
--EL OBJETO DESTINO DEBE EXISTIR
--SINTAXIS:
--INSERT INTO DESTINO FROM ORIGIN
insert into departamentos select * from dept
--2) SELECT...INTO
--ESTA CONSULTA CREA EL OBJETO E INSERTA REGISTROS
--SOLAMENTE PODEMOS EJECUTAR UNA VEZ SI EL OBJETO NO EXISTE
--SINTAXIS:
--SELECT * INTO DESTINO SELECT * FROM DEPT
select * into departamentos from dept
--
--DELETE
--SINTAXIS:
--DELETE FROM TABLA (WHERE CONDICIÓN) opcional
delete from departamentos where dept_no = 10
--MUY ÚTIL UTILIZAR SUBCONSULTAS
--RECOMENDADAS
--ELIMINAR TODOS LOS EMPLEADOS DEL DEPARTAMENTO DE SALAMANCA
delete from emp where dept_no = (select dept_no from dept where loc = 'salamanca')
--ELIMINAR REGISTROS DE TODA UNA TABLA MÁS RÁPIDO
--TRUNCATE TABLE NOMBRETABLA
--
--UPDATE
--SINTAXIS:
--UPDATE TABLA SET CAMPO1=VALOR, CAMPO2=VALOR (WHERE CONDICIÓN) opcional7
update dept set loc = 'murcia', dnombre = 'murciano' where dept_no = 60
--PODEMOS UTILIZAR SUBCONSULTAS EN TODO
--PONER A JIMÉNEZ EL MISMO SALARIO QUE TENGA NEGRO
update emp set salario = (select salario from emp where apellido = 'negro') where apellido = 'jimenez'